projects = [
            {
            "title": "Yellow Taxi Durations Prediction - MLOps Project",
            "description": "This project involves predicting the duration of yellow taxi rides in New York City using machine learning techniques.",
            "link": "https://github.com/avikumart/MLOps-Project",
            "tools": ["Python", "Scikit-learn", "Docker", "AWS", "Streamlit", "GitHub Actions", "Prefect", "MLflow", "FastAPI"]
            },
            {
            "title":"Methane Emisssions Dashboard",
            "description": "A dashboard to visualize and analyze methane emissions data, providing insights into environmental impact.",
            "link": "https://github.com/avikumart/Methane_SQL-Data-analysis-and-Dashboarding/tree/main",
            "tools": ["Python", "SQL", "MySQL","Dash", "Plotly", "Pandas", "NumPy", "GitHub","Streamlit"]
            },
            {
            "title": "Poisonous Mushroom Classification",
            "description": "A machine learning API project to classify mushrooms as poisonous or edible based on various features.",
            "link": "https://github.com/avikumart/Poisonous-Mushroom-Prediction-API-project",
            "tools": ["Python", "FastAPI", "Scikit-learn", "Pandas", "NumPy"]
            },
            {
            "title":"Wild-Blue-Berry-Yield-Prediction",
            "description": "The dataset used for predictive modelling was generated by the Wild Blueberry Pollination Simulation Model, which is an open-source, spatially-explicit computer simulation program, that enables exploration of how various factors, including plant spatial arrangement, outcrossing and self-pollination, bee species compositions and weather conditions, in isolation and combination, affect pollination efficiency and yield of the wild blueberry agro-ecosystem. The simulation model has been validated by the field observation and experimental data collected in Maine USA and Canadian Maritimes during the last 30 years and now is a useful tool for hypothesis testing and theory development for wild blueberry pollination researches. This simulated data provides researchers who have actual data collected from field observation and those who wants to experiment the potential of machine learning algorithms response to real data and computer simulation modelling generated data as input for crop yield prediction models.",
            "link":"https://github.com/avikumart/Wild-Blue-Berry-Yield-Prediction-Flask-app-deploy",
            "tools": ["Python", "Flask", "Scikit-learn", "Pandas", "NumPy", "Matplotlib", "Seaborn", "GitHub"],
            },
            {
            "title":"Road-Traffic-Severity-Classification-Project",
            "description":"This data set is collected from Addis Ababa Sub-city, Ethiopia police departments for master's research work. The data set has been prepared from manual records of road traffic accidents of the year 2017-20. All the sensitive information has been excluded during data encoding and finally, it has 32 features and 12316 instances of accident. Then it is preprocessed for identification of major causes of the accident by analyzing it using different machine learning classification algorithms.",
            "link":"https://github.com/avikumart/Road-Traffic-Severity-Classification-Project",
            "tools": ["Python", "Scikit-learn", "Pandas", "NumPy", "Matplotlib", "Seaborn", "GitHub", "streamlit","SHAP"]
            }
            ] 